### PR TITLE
broken link #23 removed-not tested yet

### PR DESCRIPTION
**Pull request by Ruutger**
Hi, i removed the broken link referring to a Fedora distro comparison site. 
Also, i have for the mean time written a short message explaining the this point. 

I have not tested the change, whether this is properly done.

NOTE for Project Master Figure002: this should be one/1 commit. Not 2.

### CODE REVIEW

**Comment by figure002** [comment]
Hi, thanks for the pull request, but this is not going to work. Please leave the translation as is; that's something the translators can fix. The link should be removed in `lib/views/switch_to_linux.choose_a_distribution.php`. Could you update your pull request?

**Comment by Ruutger** [comment]
Mail even snel zo. Ga vd week proberen te verbeteren ok.
Dacht dat hpje zei via local file.  Maar ga naar kijken.

Mvg,

Rutger
Op 29 mei 2016 15:42 schreef "Serrano Pereira" <notifications@github.com>:

**Comment by Ruutger** [comment]
Deleted the broken link about Fedora distro's

Hopefully properly this time;-)

**Comment by figure002** [comment]
That'll work, thanks! But for good practice, could you create a separate feature branch instead, push your changes there, and make a pull request for your feature branch? That way your master branch stays clean and you can easily sync your master branch with remote by doing a `git pull`. Bonus points if you include the ticket number in your commit message (e.g. "Fix broken link (fixes #23)"), which will automatically close the ticket as well.

**Pull request closed without merging**
